# Gunakan image PHP 8.2 untuk Laravel
FROM php:8.2-fpm

# Install ekstensi yang dibutuhkan oleh Laravel
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql

# Install Composer (untuk dependensi Laravel)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory di dalam container
WORKDIR /var/www

# Salin file Laravel ke dalam container
COPY . .

# Install dependensi Laravel
RUN composer install

# Set permission untuk direktori storage dan bootstrap/cache
RUN chmod -R 777 storage bootstrap/cache

EXPOSE 9000

# Jalankan php-fpm server
CMD ["php-fpm"]
